srcery-colors/srcery-vim

colors/srcery.vim
This pull request fixes a problem where misnamed color constants prevented certain tokens from being highlighted (the most important being ruby symbols).
=> Fix for misnamed color constant

colors/srcery.vim
Previously the tab bar didn't show any entries, since both the
text color and background were black.
I use neovim 0.1.5 on arch linux, not sure whether this is an issue
=> Fixed the tab bar colors

autoload/airline/themes/srcery.vim
Fixed the middle color of normal mode to mimic lightline a bit more.  Thought first that having the same color for both the cursorline and statusline clashed to much, but after trying to make the colors for newsboat, it made more sense to mimic your color choice for the statusline.  Even though they are identical.
Still a bit unsure about the ctrlp and inactive color.  The black seems a bit to blue instead of dark brown.  Thoughts?
=> airline: fixed some color mishaps

colors/srcery.vim
[Announced](https://www.vim.org/vim-8.1-released.php) with Vim 8.1.
=> Added custom color for the built-in terminal

colors/srcery.vim
Removing inverse video from cursor. Had so many problems and weird edge cases where an inverted cursor does not work. I've been forcing the cursor color to yellow in my terminal for a while now and I got to say I prefer it way. Any objections? @MindTooth
=> Change cursor to foreground black, background yellow

colors/srcery.vim
These highlights used the undefined `SrceryWhiteAlt`, thus make them fallback to fg which looks distracting. After experimenting for a while, I've come to a conclusion that xgray3 would fit the best for `list` characters.
=> Replace orphaned color used to highlight NonText and SpecialKey

.travis.yml
Now that the default image for building Travis CI is changed,
I feel that a test is warranted.
=> Remove explicit vim-vint version

README.md
I noticed vim-sneak appeared twice in the list so I removed one.
I also sorted the list alphabetically while I'm at it :)
=> doc: remove duplicate vim-sneak in plugins list, sort alphabetically

colors/srcery.vim
Italic types (toggled by `g:srcery_italic_types`)-
before:
after:
=> Italic types, TSParameter, telescope

README.md, colors/srcery.vim
This pull request introduce a new variable `g:srcery_guisp_fallback` that can enable highlighting on words that is supposed to have a colored underline/undercurl in environments that have underline/undercurl disabled or not working (terminal vim)
This pull request fixes issue #61
=> feat: add guisp fallback

README.md, colors/srcery.vim
I've done some revisions on markdown and javascript, mostly markdown.
I used the [plasticboy markdown](https://github.com/plasticboy/vim-markdown) before but I had to switch to [tpope markdown](https://github.com/tpope/vim-markdown), and I disliked how things looked. Markdown is mostly used for prose, so having a ton of color can be a bit distracting in my opinion. 
Second is some javascript revisions, I tried to get builtin and [pangloss javascript](https://github.com/pangloss/vim-javascript) looking somewhat similar, and various minor tweaks.
=> Markdown and javascript revisions

colors/srcery.vim
We've been multiple requests about tree sitter. I'm not usually using it myself, but I got started based on this https://github.com/sainnhe/sonokai/blob/257500b85cc650c9606393021a001dfd58b46e88/colors/sonokai.vim#L324-L378
I'll keep pushing to this branch with updates while I get used to treesitter.
=> feat: nvim-treesitter

README.md
fix #79.
LONG LIFE OF VI IMPROVED!!!
=> docs: fix path again for native vim 8 installation

README.md, doc/srcery.txt
Since the new refactor #84 srcery relies on the autoload functionality of vim. This pull request addresses missing explanation on how to install.
Closes #88 
Closes #89
=> fix: Missing new install instructions

colors/srcery.vim
Setup backward compatibility to nvim 0.5.x
closes #93
=> fix: update lsp hl groups to latest

colors/srcery.vim
PmenuThumb is not visible in, for example, nvim-cmp's completion window. This is due to the fact that the thumb has the same color of the background, rendering it de-facto invisible.
=> fix: PmenuThumb has the same color of the bar.

after/plugin/srcery.vim
I think there are some new 0.9.0 highlight groups too. They are probably default-linked to some sensible groups so, maybe, I'll look into those in the future.
=> Support Neovim 0.8.0 tree-sitter highlight groups.

README.md, after/syntax/html.vim, autoload/srcery.vim, colors/srcery.vim, doc/srcery.txt
Srcery already has a vim-only option to set the terminal background to hard_black. This commit adds another option, g:srcery_hard_black_gui_bg, compatible with the termguicolors (both Vim and Neovim) set-option.
=> Add option to set bg to hard_black for gui.

after/syntax/html.vim, after/syntax/javascript.vim
Fix/js vue html issues + feat
=============================
- I linked the hl group `javaScript` to normal. This makes inline `<script>` blocks in html much nicer, and fixes javavscript highlighting in [vim-vue](https://github.com/posva/vim-vue) plugin. 
- I've also sorted and and cleaned up the javascript syntax file
- there is one feat commit here, despite the branch name, it clears some syntax hl groups for javascript, so that it'll fall back to what is defined top level (symbol, statement etc(colors/srcery.vim)) This adds some needed variety to js colors, and brings it more inline with other languages.
> Keeping this as a draft for now, because I can't understand why the html plugin would set `javaScript` to `Special`. I first thought it had something to do with a couple of syntax …
=> Fix/js vue html issues + feat

README.md, autoload/srcery.vim, doc/srcery.txt
\_cterm globals has been added for configuring the extra colors in 256-color terminal emulators.
This resolves GH-106.
=> feat: make cterm colors configurable

doc/srcery.txt
* Remove spaces before tabs and extra blank lines
* Normalize hexadecimal colors and headers in color table to uppercase
* Wrap lone lines
=> fix: nitpick doc formatting

colors/srcery.vim
Fixes #112
When linking operator to normal, it'll set the background as well, which we don't want.
@flaamjab can you confirm this is working for you?
=> fix: link Operator to SrceryBrightWhite

colors/srcery.vim
This brings popup windows more in line with each other. The change was prompted by `ChatGPT.nvim` plugin that use telescope as a dependency, but the borders looked off.
`NormalFloat` was linked to `Pmenu`, `Pmenu` is used for completion, and needs to be a different background color than NormalFloat, so I set NormalFloat to srcery_black
`FloatBorder` was linked via `FloatBorder` -> `WinSeparator` -> `VertSplit` which is set to `bright_white`, but Telescope uses white as the border color, so I define that for `FloatBorder` as well
```viml
call s:HL('VertSplit', s:bright_white, g:srcery_bg)
```
=> fix: define NormalFloat and FloatBorder

colors/srcery.vim
Issue was introduced with 2e9b1d4, defining NormalFloat to srcery_bg was a bad idea and broke other popups, due to lacking background contrast.
I left in the border fix though, so that popup borders match what's configured for telescope.
This still leaves some plugin borders looking a bit off, especially if they configure the background to something other than NormalFloat.
Fixes: #115
=> fix: no contrast issue for lsp popups

colors/srcery.vim
Neovim version `0.10` unlinked `NormalFloat` with `pmenu`, which caused the popup background color to default to undefined (black/magenta etc depending on what the default colorscheme is)
Should fix the issue reported by @milogert on discord, and return the previous colors
Ref: #119, #111, #116
=> fix: define NormalFloat

colors/srcery.vim
Fix/nvim 0.10 - Define CurSearch
=====
Define CurSearch along the other search highlights, set it to use xgray/inverse, and be underline and bold. Tweak existing search groups to work with new CurSearch,
Seems some defaults changed or this hl group got added in nvim 0.10, `CurSearch` is the `hlsearch` word under the cursor. It was set to default colorscheme yellow, which messed with text selection, and don't work with how search is colorized in srcery.
Ref: #120
=> Fix/nvim 0.10 - Define CurSearch

colors/srcery.vim
These variables doesn't exist when the colorscheme is loaded, config
have to be re-sourced to get the correct colors. Holdover from refactor.
=> fix: fix conditional loading of plugin colors

colors/srcery.vim
=> fix: adjust highlights for common LazyVim plugins
